### ISSUE TITLE
It's broken

### ISSUE THREAD

**Issue by Crazygird** [Paxxous/blooket-pin-finder#1]
The shell says 

_Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
  File "<string>", line 17, in getAndSee
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)_

**Comment by Paxxous** [comment]
I haven't worked on this (or used python for that matter) for over eight months. But when messing around with the blooket api I've found that they've developed some form of protection for guessing pins (punch random pins into blooket and see what I mean). I've also checked and found that the subdomain that verified pins was down, which led to the error.

All the first lines of the error don't matter (it's just some threading errors) except for the last three, which just say the json module had trouble decrypting an empty string from the nonexistent domain name.

Sorry about that. I'm not going to keep working on this, but you can make a fork if you really want and work with proxy's or something.

**Comment by Crazygird** [comment]
cool
